joint_names: [ 'neck_axis0','neck_axis1','neck_axis2',
               'shoulder_right_axis0','shoulder_right_axis1','shoulder_right_axis2',
               'elbow_right_axis0', 'elbow_right_axis1',
               'wrist_right_axis0','wrist_right_axis1','wrist_right_axis2',
               'shoulder_left_axis0','shoulder_left_axis1','shoulder_left_axis2',
               'elbow_left_axis0', 'elbow_left_axis1',
               'wrist_left_axis0','wrist_left_axis1','wrist_left_axis2']
endeffectors: ['hand_right','hand_left','head']
hand_right:
  base_link: 'torso'
  joints: ['shoulder_right_axis0','shoulder_right_axis1','shoulder_right_axis2',
           'elbow_right_axis0','elbow_right_axis1',
           'wrist_right_axis0','wrist_right_axis1','wrist_right_axis2']
hand_left:
  base_link: 'torso'
  joints: ['shoulder_left_axis0','shoulder_left_axis1','shoulder_left_axis2',
           'elbow_left_axis0','elbow_left_axis1',
           'wrist_left_axis0','wrist_left_axis1','wrist_left_axis2']
head:
  base_link: 'torso'
  joints: ['neck_axis0','neck_axis1','neck_axis2']