head:
  motor_ids: [20,21,22,23,24,25]
  use_motor_config: true
  endeffector: "head"
shoulder_left:
  motor_ids: [0,1,2,3,4,5,6,7,16,17] #[7,6,5,4,3,2,1,0,16,17] #[0,1,2,3,4,5,6,7,16,17] # ,2
  use_motor_config: true
  endeffector: "hand_left"
shoulder_right:
  motor_ids: [8,9,10,11,12,13,14,15,19] # 18, 19
  use_motor_config: true
  endeffector: "hand_right"
wrist_left:
  motor_ids: [26,27,28,30]
  use_motor_config: true
  endeffector: "hand_left"
wrist_right:
  motor_ids: [32,33,35,37] # 32,36 ,34
  use_motor_config: true
  endeffector: "hand_right"
hand_right:
  motor_ids: [42,43,44,45]
  use_motor_config: true
  endeffector: "hand_right"
  max_setpoints: [825, 950, 1000, 1000]
hand_left:
  motor_ids: [40,41,38,39]
  use_motor_config: true
  endeffector: "hand_left"
  max_setpoints: [775, 900, 1000, 1000]
spine:
  motor_ids: [47, 48, 49, 50, 46,50,51]
